kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-car
  labels:
    type: local
    app: postgres-car
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-car
  labels:
    app: postgres-user
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
