version: "3"
services:
  app:
    build: .
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    depends_on:
      - postgres
    environment:
      APP_SECRET: tcc_medina
      DB_URL: postgresql://postgres:postgres@postgres:5432/tcc
      DB_DIALECT: postgres
      NODE_ENV: production
      PORT: 3000
    ports:
      - "80:3000"

  postgres:
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tcc