apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-crud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: ms-user-crud
          image: gmedina197/ms-user-crud:latest
          env:
            - name: DB_URL
              value: postgresql://postgresadmin:admin123@172.17.0.3:5432/postgresdb
            - name: DB_DIALECT
              value: postgres
            - name: AUTH_URL
              value: http://authentication-deployment:5000/authenticate
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 3000
