apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: ms-user-crud
        image: gmedina197/ms-user-crud
        ports:
        - containerPort: 3000