apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-user-db
spec:
  serviceName: "postgres-user"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: postgredb-user
          volumeMounts:
            - name: postgredb-user
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgredb-user
          persistentVolumeClaim:
            claimName: postgres-pv-claim-user
