apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-authorization
  template:
    metadata:
      labels:
        app: nodejs-authorization
    spec:
      containers:
        - name: ms-authorization
          image: gmedina197/ms-authorization:latest
          env:
            - name: DB_URL
              value: postgresql://postgresadmin:admin123@postgres:5432/postgresdb
            - name: DB_DIALECT
              value: postgres
            - name: PORT
              value: "5000"
            - name: APP_SECRET
              value: tccmedina
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 5000
