apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite
spec:
  selector:
    matchLabels:
      app: sqlite
  template:
    metadata:
      labels:
        app: sqlite
    spec:
      containers:
        - name: sqlite
          image: nouchka/sqlite3
          #resources:
          #  limits:
          #    memory: 512Mi
          #    cpu: "1"
          #  requests:
          #    memory: 256Mi
          #    cpu: "0.2"
          ports:
            - containerPort: 3306
              name: sqlite
          volumeMounts:
            - name: sqlite-persistent-storage
              mountPath: /var/lib/db
      volumes:
        - name: sqlite-persistent-storage
          persistentVolumeClaim:
            claimName: sqlite-pv-claim

    