apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tcc-ingress
  labels:
      name: tcc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: tcc.info
    http:
      paths:
      - pathType: Prefix
        path: /users/
        backend:
          service:
            name: user-service
            port: 
              number: 3000
      - pathType: Prefix
        path: /auth/
        backend:
          service:
            name: auth-service
            port: 
              number: 5000
      
